### ISSUE TITLE
Website on mobile freezes on load when there are too many tasks

### ISSUE THREAD

**Issue by aantsu3** [chiyadev/genshin-schedule#32] opened 2021-01-16 10:05 UTC
On pc it's working fine, but on mobile it's like this: I can't change resin, check tasks done and even see map and domain. Check it on Chrome, Opera. And it's working like this when I log in to my account, without log in it's working fine. 
![Screenshot_20210116-150104_Chrome](https://user-images.githubusercontent.com/77245268/104809027-1b8cdb80-580c-11eb-8b5b-3297ba1ff31f.jpg)
![Screenshot_20210116-150128_Chrome](https://user-images.githubusercontent.com/77245268/104809033-25164380-580c-11eb-8ed4-9a4ae243493a.jpg)

**Comment by luaneko** [comment] 2021-05-30 02:21
Closing this issue due to the lack of information. I cannot reproduce this issue on my iPhone and I haven't received any similar reports recently, so this is assumed fixed.

**Closed as completed by luaneko** 2021-05-30 02:21 UTC
Labels: bug, wontfix, performance, high-priority
